apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: {{component_application}}-stage-{{epoch}}
  namespace: rhoai-tenant
  labels:
    konflux-release-data/rbc-release-commit: {{rbc_release_commit}}
    konflux-release-data/artifact-type: components
    konflux-release-data/environment: stage
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-{{hyphenized-rhoai-version}}-components-stage
  snapshot: {{component_application}}-{{epoch}}
